apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubetest-web
  name: kubetest-web
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: kubetest-web
